// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	response "github.com/cpartogi/foodmenu/schema/response"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

func (_m *Usecase) MenuType(ctx context.Context) (mt []response.MenuType, err error) {
	ret := _m.Called(ctx)

	var r0 []response.MenuType
	if rf, ok := ret.Get(0).(func(context.Context) []response.MenuType); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).([]response.MenuType)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
